services:
  # PostgreSQL Database for IAM Service
  postgres-iam:
    extends:
      file: compose.base.yaml
      service: postgres-iam

  # RabbitMQ for IAM Service
  rabbitmq-iam:
    extends:
      file: compose.base.yaml
      service: rabbitmq-iam

  # MailHog for local email testing
  mailhog:
    extends:
      file: compose.base.yaml
      service: mailhog

networks:
  iam-service-network:
    name: foundation-iam-network-dev
    external: false

volumes:
  postgres_iam_data:
    name: iqkv_iam_postgres_data_dev
  rabbitmq_iam_data:
    name: iqkv_iam_rabbitmq_data_dev
